version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:529088255229:task-definition/spring-demo-task-def:1"
        LoadBalancerInfo:
          ContainerName: "springboot"  # Your container name in the task definition
          ContainerPort: 8080  # The port your container listens on
