version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<Task_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "springboot"  # Your container name in the task definition
          ContainerPort: 8080  # The port your container listens on
