version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - echo Logging in to Amazon ECR....
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/springboot-demo-ecr  # Dynamic repository URI
      - IMAGE_TAG=$(git rev-parse --short HEAD)  # Get short Git commit ID (7 characters)
  build:
    commands:
      - echo Build started on `date`
      - echo building the Jar file
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo pushing to repo
      - docker push $REPOSITORY_URI:$IMAGE_TAG  # Pushing the short Git commit ID tag
      - echo Writing image definitions file...
      - DOCKER_CONTAINER_NAME=springboot
      - printf '[{"name":"%s","imageUri":"%s"}]' $DOCKER_CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $DOCKER_CONTAINER_NAME
      - echo printing imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - target/springboot-aws-deploy.jar
    - appspec.yaml

env:
  variables:
    AWS_ACCOUNT_ID: "529088255229"  # You can also set this as an environment variable in CodeBuild
    DOCKER_USERNAME: "hari796"
    DOCKER_PASSWORD: "Hari@1234"
