version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.ap-south-1.amazonaws.com/springboot-demo-ecr  # Dynamic repository URI
      
      # Using the last 7 characters of the CodeBuild build ID for the image tag
      - IMAGE_TAG=$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}' | tail -c 8)
      - echo "Using IMAGE_TAG: $IMAGE_TAG"

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Jar file...
      - mvn clean install
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing to Amazon ECR...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' springboot $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo "imagedefinitions.json created:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - target/springboot-aws-deploy.jar
    - appspec.yaml

env:
  variables:
    REPOSITORY_URI: "529088255229.dkr.ecr.ap-south-1.amazonaws.com/springboot-demo-ecr"
    IMAGE_TAG: "latest"
    DOCKER_USERNAME: "hari796"
    DOCKER_PASSWORD: "Hari@1234"
